### PR TITLE
Upgrade package

### LINKED ISSUE #11: Add esm support
Bundling the code should solve this issue.

### PR DESCRIPTION
**Pull request by bryanjtc**
Fixes: #11 
Upgrades yarn to v3
Adds swc as the default loader for jest
Bundles code with tsup

### CODE REVIEW

**Comment by ccpu** [comment]
Thank you for the PR. Unfortunately, I cannot accept this PR because it involves too many changes. 
Since I started this project, I made a copy of [vega/ts-json-schema-generator](https://github.com/vega/ts-json-schema-generator) rather than forking, which was a big mistake since in order to update the project with [vega/ts-json-schema-generator](https://github.com/vega/ts-json-schema-generator) I have to copy all the files over and apply the changes visually. Therefore, I'd like to keep the modified files as minimal as possible.

I would suggest you use the original library [vega/ts-json-schema-generator](https://github.com/vega/ts-json-schema-generator) as it's actively updated.

**Comment by bryanjtc** [comment]
I will simplify the pr

**Comment by bryanjtc** [comment]
A few notes:
- Minify jest tests were failing because a minify option isn't implemented in the project, so I removed those tests. I also removed the option from `Config.ts`
- Dropped support for node 10 and 12. These versions are no longer maintained and don't work with tsup (code bundler). The CI workflow file and the engines field in `package.json` were updated with this change.
- The `ts-to-json.ts` file had a type error related to commander, so I fixed it.
- `tsconfig.json` included a file that didn't exist, I replaced it with the correct one.
- Since all code is bundled now, the file in bin folder is not longer needed. `README.md` is updated with this change.
- Added the module and exports field in `package.json` for esm compability.
- Added the files field in `package.json` to reduce the publish size. By default npm publishes the content of the files field, the `package.json` and the `README.md`
- Since jest now uses swc, the `babel.config.js` is no longer needed. It was deleted.

**Comment by bryanjtc** [comment]
@ccpu PR is now simplified.

**Comment by ccpu** [comment]
Thank you for the PR. It has been merged.

**Comment by ccpu** [comment]
Unfortunately, I must revert this PR because it has been problematic. This library is being used for a website/storybook that I am working on, and apparently the new bundling system does not play well with webpack. An error message appears saying that it cannot find the module 'fs'. I am using storybook 6.4 and I included 'fs: 'empty' to storybook webpack, but it didn't work. Sorry!

**Pull request merged**
